GET http://localhost:3001/api/word_game?sentence=the sentence you want to analyze HTTP/1.1
content-type: application/json

###
POST http://localhost:5501/api/phonebill/total HTTP/1.1
content-type: application/json
{
  "bill": "call,sms"
}
###
POST http://localhost:5501/api/phonebill/price HTTP/1.1
content-type: application/json

###
GET http://localhost:5000/api/phonebill/prices HTTP/1.1
content-type: application/json

###
POST http://localhost:5000/api/enough HTTP/1.1
content-type: application/json
{
   "usage": "call,sms,call",
   "available" : 54
}